# Generated by Django 6.0.2 on 2026-02-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('certificate_of_incorporation', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_type', models.CharField(max_length=100)),
                ('issuance_date', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('total_members', models.IntegerField(default=0)),
                ('date_of_election', models.DateField(blank=True, null=True)),
                ('term_of_office', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('No legal standing', 'No legal standing'), ('Dissolved', 'Dissolved'), ('Revoked', 'Revoked'), ('Term expired', 'Term expired'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeOfViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('violation_sec_64', models.BooleanField(default=False, verbose_name='Section 64')),
                ('violation_sec_101', models.BooleanField(default=False, verbose_name='Section 101')),
                ('violation_sec_62', models.BooleanField(default=False, verbose_name='Section 62')),
                ('date_issued', models.DateField()),
                ('evaluator', models.CharField(max_length=150)),
                ('hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novs', to='HoaRegistry.hoaprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderForInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('penalties', models.CharField(choices=[('1', 'Censure'), ('2', 'Fine'), ('3', 'Suspension of Privileges'), ('4', 'Suspension of Board'), ('5', 'Removal of Officers'), ('6', 'Revocation')], max_length=50)),
                ('date_issued', models.DateField()),
                ('evaluator', models.CharField(max_length=150)),
                ('mr_status', models.CharField(max_length=100)),
                ('hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='HoaRegistry.hoaprofile')),
                ('nov_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HoaRegistry.noticeofviolation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderToPerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('submission_comment', models.TextField()),
                ('date_issued', models.DateField()),
                ('evaluator', models.CharField(max_length=150)),
                ('mr_status', models.CharField(help_text='Motion for Reconsideration Status', max_length=100)),
                ('hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='HoaRegistry.hoaprofile')),
                ('nov_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HoaRegistry.noticeofviolation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
