# Generated by Django 6.0.2 on 2026-03-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0004_projectapplication_date_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='cr_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CR No.'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='ls_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LS No.'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='main_or_compliance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='status_of_application',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='type_of_application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
